theme: jekyll-theme-minimal
markdown: kramdown
github: is\_project\_page:false
name: Marco Wilhelm
title: Dipl. Math. Marco Wilhelm
description: Personal website of Marco Wilhelm, research assistant at the Department of Computer Science, TU Dortmund (Germany)
logo: wilhelm.jpg
