theme: jekyll-theme-minimal
markdown: kramdown
github: is\_project\_page:false
name: Marco Wilhelm
title: Marco Wilhelm
description: Personal website of Marco Wilhelm, research assistant at TU Dortmund, Germany
logo: wilhelm.jpg
